DROP TABLE NAUCZYCIEL CASCADE CONSTRAINTS;
DROP TABLE UCZEN CASCADE CONSTRAINTS;
DROP TABLE PRZEDMIOT CASCADE CONSTRAINTS;
DROP TABLE OCENA CASCADE CONSTRAINTS;
DROP TABLE OCENIANIE CASCADE CONSTRAINTS;
CREATE TABLE NAUCZYCIEL ( "idn" int not null, "teachers surname" char(30) not null, "teachers name" char(20) not null, constraint NAUCZYCIEL_PK PRIMARY KEY ("idn"));
CREATE TABLE UCZEN ( "idu" int not null, "students surname" char(30) not null, "students name" char(20) not null, constraint UCZEN_PK PRIMARY KEY ("idu"));
CREATE TABLE PRZEDMIOT ("idp" int not null, "class" char(20) not null, constraint PRZEDMIOT_PK PRIMARY KEY ("idp"));
CREATE TABLE OCENA ("ido" int not null, "string" char(20) not null, "numeric" FLOAT not null, constraint OCENA_PK PRIMARY KEY ("ido"));
CREATE TABLE OCENIANIE ( "idn" int not null, "idu" int not null, "idp" int not null, "ido" int not null, "type of grade" char(1) not null);
ALTER TABLE "OCENIANIE" ADD CONSTRAINT "OCENIANIE_fk0" FOREIGN KEY ("idn") REFERENCES NAUCZYCIEL("idn");
ALTER TABLE "OCENIANIE" ADD CONSTRAINT "OCENIANIE_fk1" FOREIGN KEY ("idu") REFERENCES UCZEN("idu");
ALTER TABLE "OCENIANIE" ADD CONSTRAINT "OCENIANIE_fk2" FOREIGN KEY ("idp") REFERENCES PRZEDMIOT("idp");
ALTER TABLE "OCENIANIE" ADD CONSTRAINT "OCENIANIE_fk3" FOREIGN KEY ("ido") REFERENCES OCENA("ido");
INSERT INTO NAUCZYCIEL("idn", "teachers surname", "teachers name") VALUES(1, 'Kowalski', 'Jan');
INSERT INTO NAUCZYCIEL("idn", "teachers surname", "teachers name") VALUES(2, 'Nowak', 'Piotr');
INSERT INTO NAUCZYCIEL("idn", "teachers surname", "teachers name") VALUES(3, 'Wojcik', 'Agata');
INSERT INTO NAUCZYCIEL("idn", "teachers surname", "teachers name") VALUES(4, 'Zasada', 'Mateusz');
INSERT INTO NAUCZYCIEL("idn", "teachers surname", "teachers name") VALUES(5, 'Syta', 'Paulina');
INSERT INTO NAUCZYCIEL("idn", "teachers surname", "teachers name") VALUES(6, 'Kowalczyk', 'Diana');
INSERT INTO PRZEDMIOT("idp", "class") VALUES (1, 'WF');
INSERT INTO PRZEDMIOT("idp", "class") VALUES (2, 'Matematyka');
INSERT INTO PRZEDMIOT("idp", "class") VALUES (3, 'Przyroda');
INSERT INTO PRZEDMIOT("idp", "class") VALUES (4, 'Fizyka');
INSERT INTO PRZEDMIOT("idp", "class") VALUES (5, 'Polski');
INSERT INTO PRZEDMIOT("idp", "class") VALUES (6, 'Angielski');
INSERT INTO UCZEN ("idu", "students surname", "students name") VALUES (1, 'Podlasinki', 'Marcin');
INSERT INTO UCZEN ("idu", "students surname", "students name") VALUES (2, 'Piecyk', 'Pawel');
INSERT INTO UCZEN ("idu", "students surname", "students name") VALUES (3, 'Sek', 'Dominik');
INSERT INTO UCZEN ("idu", "students surname", "students name") VALUES (4, 'Lepecki', 'Lukasz');
INSERT INTO UCZEN ("idu", "students surname", "students name") VALUES (5, 'Nowak', 'Michal');
INSERT INTO UCZEN ("idu", "students surname", "students name") VALUES (6, 'Gruszka', 'Lukasz');
INSERT INTO OCENA ("ido", "string", "numeric") VALUES (1, 'ndst', 1);
INSERT INTO OCENA ("ido", "string", "numeric") VALUES (2, 'dop', 2);
INSERT INTO OCENA ("ido", "string", "numeric") VALUES (3, 'dst', 3);
INSERT INTO OCENA ("ido", "string", "numeric") VALUES (4, 'db', 4);
INSERT INTO OCENA ("ido", "string", "numeric") VALUES (5, 'bdb', 5);
INSERT INTO OCENA ("ido", "string", "numeric") VALUES (6, 'cel', 6);
